---
apiVersion: v1
kind: Service
metadata:
  name: chango-data-api-service
  namespace: {{ .Values.namespace }}
  labels:
    app: chango-data-api
    component: chango
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: rest
      protocol: TCP
      name: rest
    - port: {{ .Values.jetty.server.port }}
      targetPort: jetty
      protocol: TCP
      name: jetty
  selector:
    app: chango-data-api
