---
#####################
# profile: common
#####################

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    db:
      enabled: false
  server:
    port: 38081

server:
  port: 8088
  servlet:
    context-path: /
  shutdown: graceful


---
#####################
# profile: dev
#####################
spring:
  profiles: dev


---
#####################
# profile: prod
#####################
spring:
  profiles: prod
