namespace: rest-catalog
serviceAccount: rest-catalog
image: cloudcheflabs/rest-catalog:v1.0.0
imagePullPolicy: Always
imagePullSecrets: {}
replicas: 1
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 5Gi
priorityClassName: ""
annotations: {}
affinity: {}
tolerations: {}
nodeSelector: {}
hostNetwork: false
dnsPolicy: ClusterFirst
nameOverride: ""


# hpa.
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50

# jetty ingress.
jettyIngress:
  enabled: false
  ingressClassName: nginx
  hostName: rest-catalog-jetty-oci.cloudchef-labs.com


# iceberg rest catalog server environment variable values.
restCatalog:
  token: "any-rest-catalog-token-12345"
  warehouse: "any-warehouse-location"
  s3:
    accessKey: "any-s3-access-key"
    secretKey: "any-s3-secret-key"
    endpoint: "any-s3-endpoint"
  jdbc:
    url: "jdbc:mysql://localhost:3306/rest_catalog?useSSL=false&createDatabaseIfNotExist=true"
    user: "any-user"
    password: "any-password"



# cert-manager.
certManager:
  clusterIssue: letsencrypt-prod


# spring boot server
server:
  port : 8080

# embedded jetty server port.
jetty:
  server:
    port: 8181


# spring profile.
spring:
  profiles:
    active: prod


# spring boot management server.
management:
  server:
    port: 38081

# readiness probe.
readiness:
  initialDelaySeconds: 5
  periodSeconds: 5

# liveness probe.
liveness:
  initialDelaySeconds: 5
  periodSeconds: 5
