apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-catalog
  labels:
    app: rest-catalog
    component: chango
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: rest-catalog
      component: chango
  template:
    metadata:
      labels:
        app: rest-catalog
        component: chango
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      serviceAccountName: {{ .Values.serviceAccount }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      containers:
        - name: rest-catalog
          image: {{ .Values.image }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.spring.profiles.active }}"
            - name: REST_CATALOG_ACCESS_TOKEN
              value: "{{ .Values.restCatalog.token }}"
            - name: CATALOG_WAREHOUSE
              value: "{{ .Values.restCatalog.warehouse }}"
            - name: S3_ACCESS_KEY
              value: "{{ .Values.restCatalog.s3.accessKey }}"
            - name: S3_SECRET_KEY
              value: "{{ .Values.restCatalog.s3.secretKey }}"
            - name: S3_ENDPOINT
              value: "{{ .Values.restCatalog.s3.endpoint }}"
            - name: JDBC_URL
              value: "{{ .Values.restCatalog.jdbc.url }}"
            - name: JDBC_USER
              value: "{{ .Values.restCatalog.jdbc.user }}"
            - name: JDBC_PASSWORD
              value: "{{ .Values.restCatalog.jdbc.password }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources: 
          {{- toYaml $.Values.resources | nindent 12 }}
          command:
            - "./run-rest-catalog.sh"
          volumeMounts:
            - name: rest-catalog-volume
              mountPath: /opt/rest-catalog/conf/application.yml
              subPath: application.yml
          ports:
            - name: jetty
              containerPort: {{ .Values.jetty.server.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.management.server.port }}
            initialDelaySeconds: {{ .Values.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.management.server.port }}
            initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.liveness.periodSeconds }}
          lifecycle:
            preStop:
              exec:
                command: [ "sleep", "15" ]
      volumes:
        - name: rest-catalog-volume
          configMap:
            name: rest-catalog