apiVersion: apps/v1
kind: Deployment
metadata:
  name: chango-data-api
  labels:
    app: chango-data-api
    component: chango
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: chango-data-api
      component: chango
  template:
    metadata:
      labels:
        app: chango-data-api
        component: chango
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      serviceAccountName: {{ .Values.serviceAccount }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      containers:
        - name: chango-data-api
          image: {{ .Values.image }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.spring.profiles.active }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources: 
          {{- toYaml $.Values.resources | nindent 12 }}
          command:
            - "./run-rest-catalog.sh"
          volumeMounts:
            - name: chango-data-api-volume
              mountPath: /opt/chango-data-api/conf/application.yml
              subPath: application.yml
          ports:
            - name: rest
              containerPort: {{ .Values.server.port }}
              protocol: TCP
            - name: jetty
              containerPort: {{ .Values.jetty.server.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.management.server.port }}
            initialDelaySeconds: {{ .Values.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.management.server.port }}
            initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.liveness.periodSeconds }}
          lifecycle:
            preStop:
              exec:
                command: [ "sleep", "15" ]
      volumes:
        - name: chango-data-api-volume
          configMap:
            name: chango-data-api