---
apiVersion: v1
kind: Service
metadata:
  name: rest-catalog-service
  namespace: {{ .Values.namespace }}
  labels:
    app: rest-catalog
    component: chango
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.jetty.server.port }}
      targetPort: jetty
      protocol: TCP
      name: jetty
  selector:
    app: rest-catalog
